# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03b_utils.misc.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/03b_utils.misc.ipynb 5
import numpy as np
import jax, jax.numpy as jnp

from fastcore.test import test_eq

# %% ../../nbs/03b_utils.misc.ipynb 6
def to_numpy(t):
    if t.dtype == jnp.bfloat16:
        t = np.array(t, dtype=np.float32)
    return t

# %% ../../nbs/03b_utils.misc.ipynb 7
def is_cpu(t: jax.Array):
    return t.device() == jax.devices("cpu")[0]


# %% ../../nbs/03b_utils.misc.ipynb 8
def test_array_repr(r: str, template:str):
    # Depending on the jax version, the arrray type can be either "Array" or "DeviceArray".
    # The remplate repr is of Array tyoe, but if our array is DeviceArray, it will be fine
    # too.

    if not ((template == r) or (template.replace("Array", "DeviceArray") == r)):
        print(f"template: {template}")
        print(f"r: {r}")
        raise Exception("The array repr is not as expected")

test_array_repr("DeviceArray[2] μ=-0.466 σ=1.515 gpu:0 [-1.981, 1.048]",
                "Array[2] μ=-0.466 σ=1.515 gpu:0 [-1.981, 1.048]")
