project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    # toc: true
    page-layout: full

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "http://github.com/xl0/lovely-jax/"
  sidebar:
    style: floating

default-image-extension: ""
metadata-files: [nbdev.yml, sidebar.yml]