# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lovely-jax',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/lovely-jax',
                'lib_path': 'lovely_jax'},
  'syms': {'lovely_jax.core': {'lovely_jax.core.foo': ('core.html#foo', 'lovely_jax/core.py')}}}